import { PostmanProvider } from "./postman";

export class QuickbooksProvider extends PostmanProvider {
  constructor() {
    super({
      name: "Quickbooks",
      description:
        "Intuit QuickBooks is small business financial software supporting small business start-ups to track, organize, and manage their finances.",
      logoUrl: "https://logo.clearbit.com/quickbooks.com",
      versions: ["V3"],
      postmanCollectionId: "12143221-f27bc33f-082f-45f6-b143-cd3c7d4241da",
      docsLink: "https://developer.intuit.com/app/developer/qbo/docs/develop",
      entities: [
        "Account-Create",
        "Account-ReadById",
        "Account-Update",
        "Attachable-Create",
        "Attachable-Delete",
        "Attachable-ReadById",
        "Attachable-Update",
        "Batch",
        "Bill-Create",
        "Bill-Delete",
        "Bill-GetById",
        "Bill-Update",
        "BillPayment-Create",
        "BillPayment-Delete",
        "BillPayment-Update",
        "Class-Create",
        "Class-Delete",
        "Class-ReadById",
        "Class-Update",
        "CompanyInfo-ReadById",
        "CreditMemo-Create",
        "CreditMemo-Delete",
        "CreditMemo-ReadById",
        "CreditMemo-Update",
        "Customer-Create",
        "Customer-Delete",
        "Customer-ReadById",
        "Customer-Update",
        "Department-Create",
        "Department-Delete",
        "Department-ReadById",
        "Department-Update",
        "Deposit-Create",
        "Deposit-Delete",
        "Deposit-ReadById",
        "Deposit-Update",
        "Employee-Create",
        "Employee-Delete",
        "Employee-ReadById",
        "Employee-Update",
        "Estimate-Create",
        "Estimate-Delete",
        "Estimate-ReadById",
        "Estimate-Update",
        "Invoice-Create",
        "Invoice-Delete",
        "Invoice-ReadById",
        "Invoice-Void",
        "Item-Create",
        "Item-Delete",
        "Item-Update",
        "JournalEntry-Create",
        "JournalEntry-Delete",
        "JournalEntry-ReadById",
        "JournalEntry-Update",
        "Payment-Create",
        "Payment-Delete",
        "Payment-ReadByID",
        "Payment-Update",
        "PaymentMethod-Create",
        "PaymentMethod-Delete",
        "PaymentMethod-ReadById",
        "PaymentMethod-Update",
        "Preference-Update",
        "Purchase-Create",
        "Purchase-Delete",
        "PurchaseOrder-Create",
        "PurchaseOrder-Delete",
        "PurchaseOrder-ReadById",
        "PurchaseOrder-Update",
        "RefundReceipt-Create",
        "RefundReceipt-Delete",
        "RefundReceipt-ReadById",
        "RefundReceipt-Update",
        "Report-AccountList",
        "Report-AgedPayableDetail",
        "Report-AgedPayables",
        "Report-AgedReceivableDetail",
        "Report-AgedReceivables",
        "Report-BalanceSheet",
        "Report-CashFlow",
        "Report-CashSales",
        "Report-CustomerBalance",
        "Report-CustomerBalanceDetail",
        "Report-CustomerIncome",
        "Report-CustomerSales",
        "Report-DepartmentSales",
        "Report-GeneralLedger",
        "Report-InventoryValuationSummary",
        "Report-ItemSales",
        "Report-ProfitAndLoss",
        "Report-ProfitAndLossDetail",
        "Report-TransactionList",
        "Report-TrialBalance",
        "Report-VendorBalance",
        "Report-VendorBalanceDetail",
        "Report-VendorExpense",
        "SalesReceipt-Create",
        "SalesReceipt-Delete",
        "SalesReceipt-ReadByID",
        "SalesReceipt-Update",
        "SalesReceipt-Void",
        "TaxAgency-Create",
        "TaxAgency-ReadByID",
        "TaxService-Create",
        "Term-Create",
        "Term-Delete",
        "Term-ReadById",
        "Term-Update",
        "TimeActivity-Create",
        "TimeActivity-Delete",
        "TimeActivity-ReadById",
        "TimeActivity-Update",
        "Transfer-Create",
        "Transfer-Delete",
        "Transfer-ReadById",
        "Transfer-Update",
        "Vendor-Create",
        "Vendor-Delete",
        "Vendor-ReadById",
        "Vendor-Update",
        "VendorCredit-Delete",
        "VendorCredit-ReadById",
        "VendorCredit-Update",
      ],
      sanitizeSchema,
    });
  }
}

function sanitizeSchema(schema: unknown) {
  return JSON.parse(
    JSON.stringify(schema, (key, value) => {
      if (value?.format === "color" || value?.format === "utc-millisec" || value?.format === "style") {
        delete value.format;
      }

      return value;
    }),
  );
}
